kind: Deployment
apiVersion: apps/v1
metadata:
  name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: michaelmed/front-end
        ports:
        - containerPort: 80